name: build-android-dev
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build MoneyManagerDev Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.32.7
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter build apk --split-per-abi --flavor dev --android-project-arg qa

      - name: Upload armeabi-v7a artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoneyManager-dev-armeabi-v7a.apk
          path: build/app/outputs/apk/dev/release/app-dev-armeabi-v7a-release.apk

      - name: Upload arm64-v8a artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoneyManager-dev-arm64-v8a.apk
          path: build/app/outputs/apk/dev/release/app-dev-arm64-v8a-release.apk
